version: 2
updates:
  - package-ecosystem: "npm"
    directory: 'packages/package-a'
    schedule:
      interval: "daily"
    reviewers:
      - yashi8484
    labels:
      - "package-a"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: "daily"
    reviewers:
      - yashi8484
    labels:
      - "workspace"
      - "dependencies"
